project_id = "qaansoasbfzjsxsqpcsb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-flashcards]
    verify_jwt = false
  [functions.generate-quiz]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.process-note]
    verify_jwt = false
  [functions.smart-file]
    verify_jwt = false
  [functions.sync-calendar]
    verify_jwt = false
