// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "Lister les t\xE2ches",
  description: "List the signed-in student's Orbit tasks, optionally filtered by status.",
  inputSchema: {
    status: z.enum(["todo", "done", "all"]).default("todo").describe("Filter by status."),
    limit: z.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    let q = supabaseForUser(ctx).from("tasks").select("id,title,status,due_date,energy_level,priority_score").order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    const tasks = (data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      status: t.status,
      due_date: t.due_date,
      energy_level: t.energy_level,
      priority_score: t.priority_score
    }));
    return { content: [{ type: "text", text: JSON.stringify(tasks) }], structuredContent: { tasks } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^4.6.5";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Cr\xE9er une t\xE2che",
  description: "Create a new task in the signed-in student's Orbit task list.",
  inputSchema: {
    title: z2.string().trim().min(1).max(300).describe("Task title."),
    due_date: z2.string().optional().describe("Optional due date (ISO 8601)."),
    energy_level: z2.enum(["low", "medium", "high"]).default("medium")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, due_date, energy_level }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("tasks").insert({ user_id: ctx.getUserId(), title, due_date: due_date ?? null, energy_level }).select("id,title,status,due_date").single();
    if (error) throw new ToolError2(error.message);
    const task = { id: data.id, title: data.title, status: data.status, due_date: data.due_date };
    return { content: [{ type: "text", text: `T\xE2che cr\xE9\xE9e : ${task.title}` }], structuredContent: { task } };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^4.6.5";
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Terminer une t\xE2che",
  description: "Mark one of the signed-in student's tasks as done (or back to todo).",
  inputSchema: {
    task_id: z3.string().uuid(),
    done: z3.boolean().default(true)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id, done }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("tasks").update({ status: done ? "done" : "todo" }).eq("id", task_id).select("id,title,status").maybeSingle();
    if (error) throw new ToolError3(error.message);
    if (!data) throw new ToolError3("Task not found");
    const task = { id: data.id, title: data.title, status: data.status };
    return { content: [{ type: "text", text: `${task.title} \u2192 ${task.status}` }], structuredContent: { task } };
  }
});

// src/lib/mcp/tools/list-schedule.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^4.6.5";
var list_schedule_default = defineTool4({
  name: "list_schedule",
  title: "Emploi du temps",
  description: "List the signed-in student's upcoming classes and exams between two dates.",
  inputSchema: {
    from: z4.string().optional().describe("Start date YYYY-MM-DD (default today)."),
    to: z4.string().optional().describe("End date YYYY-MM-DD (default +7 days).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const start = from ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const end = to ?? new Date(Date.now() + 7 * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("calendar_events").select("id,title,event_date,start_time,end_time,room_number,teacher_name,event_type").gte("event_date", start).lte("event_date", end).order("event_date").order("start_time").limit(200);
    if (error) throw new ToolError4(error.message);
    const events = (data ?? []).map((e) => ({
      id: e.id,
      title: e.title,
      date: e.event_date,
      start: e.start_time,
      end: e.end_time,
      room: e.room_number,
      teacher: e.teacher_name,
      type: e.event_type
    }));
    return { content: [{ type: "text", text: JSON.stringify(events) }], structuredContent: { events } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qaansoasbfzjsxsqpcsb";
var mcp_default = defineMcp({
  name: "orbit-plan",
  title: "Orbit plan",
  version: "0.1.0",
  instructions: "Orbit is a student assistant. Use `list_schedule` for classes/exams, `list_tasks` to see tasks, `create_task` to add one, and `complete_task` to mark one done. All data belongs to the signed-in student.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_schedule_default, list_tasks_default, create_task_default, complete_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
